name: Unity CI 

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact dir
        run: |
          mkdir -p artifacts
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
